# Automatic labeling configuration for CCG project
# Based on file paths and patterns

# Core functionality changes
'core':
  - changed-files:
    - any-glob-to-any-file: 'src/ccg/core.py'

# CLI interface changes  
'cli':
  - changed-files:
    - any-glob-to-any-file: 'src/ccg/cli.py'
    - any-glob-to-any-file: 'src/ccg/__main__.py'

# Git operations changes
'git':
  - changed-files:
    - any-glob-to-any-file: 'src/ccg/git.py'

# Utilities changes
'utils':
  - changed-files:
    - any-glob-to-any-file: 'src/ccg/utils.py'

# Package initialization changes
'package':
  - changed-files:
    - any-glob-to-any-file: 'src/ccg/__init__.py'

# Script changes
'scripts':
  - changed-files:
    - any-glob-to-any-file: 'scripts/**'

# Documentation changes
'documentation':
  - changed-files:
    - any-glob-to-any-file: '*.md'
    - any-glob-to-any-file: 'docs/**'
    - any-glob-to-any-file: '.github/*.md'
    - any-glob-to-any-file: '.github/ISSUE_TEMPLATE/**'

# Configuration changes
'config':
  - changed-files:
    - any-glob-to-any-file: 'pyproject.toml'
    - any-glob-to-any-file: 'setup.py'
    - any-glob-to-any-file: '.pre-commit-config.yaml'
    - any-glob-to-any-file: '.gitignore'

# GitHub Actions and CI changes
'ci':
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'
    - any-glob-to-any-file: '.github/dependabot.yml'

# Dependencies changes
'dependencies':
  - changed-files:
    - any-glob-to-any-file: 'pyproject.toml'
    - any-glob-to-any-file: 'requirements*.txt'

# Version and release changes
'release':
  - changed-files:
    - any-glob-to-any-file: 'CHANGELOG.md'
    - any-glob-to-any-file: 'src/ccg/__init__.py'

# Build and packaging changes
'build':
  - changed-files:
    - any-glob-to-any-file: 'pyproject.toml'
    - any-glob-to-any-file: 'setup.py'
    - any-glob-to-any-file: 'scripts/bump_version.py'

# Security related changes
'security':
  - changed-files:
    - any-glob-to-any-file: '.github/SECURITY.md'

# Community and contribution changes
'community':
  - changed-files:
    - any-glob-to-any-file: '.github/CODE_OF_CONDUCT.md'
    - any-glob-to-any-file: '.github/CONTRIBUTING.md'
    - any-glob-to-any-file: '.github/PULL_REQUEST_TEMPLATE.md'
    - any-glob-to-any-file: '.github/FUNDING.yml'

# Breaking changes (look for breaking change indicators)
'breaking':
  - title: ['^.*!:', 'BREAKING CHANGE', 'BREAKING:', '^feat!:', '^fix!:', '^refactor!:']

# Feature branches
'feature':
  - title: ['^feat:', '^feature:']

# Bug fix branches
'bug':
  - title: ['^fix:', '^bug:']

# Chore branches
'chore':
  - title: ['^chore:']

# Refactor branches
'refactor':
  - title: ['^refactor:']

# Style changes
'style':
  - title: ['^style:']

# Performance improvements
'performance':
  - title: ['^perf:']
