"""Git operations and repository management."""

from .operations import (
    branch_exists_on_remote,
    check_and_install_pre_commit,
    check_has_changes,
    check_is_git_repo,
    check_remote_access,
    create_tag,
    discard_local_changes,
    edit_commit_message,
    fetch_and_pull_all,
    get_commit_by_hash,
    get_current_branch,
    get_recent_commits,
    get_repository_name,
    git_add,
    git_commit,
    git_push,
    is_git_repository,
    pull_from_remote,
    push_tag,
    run_git_command,
    show_commit_diff,
    show_diff_between_commits,
    show_enhanced_diff_between_commits,
    show_local_changes_interactive,
    show_working_directory_status,
)

__all__ = [
    "branch_exists_on_remote",
    "check_and_install_pre_commit",
    "check_has_changes",
    "check_is_git_repo",
    "check_remote_access",
    "create_tag",
    "discard_local_changes",
    "edit_commit_message",
    "fetch_and_pull_all",
    "get_commit_by_hash",
    "get_current_branch",
    "get_recent_commits",
    "get_repository_name",
    "git_add",
    "git_commit",
    "git_push",
    "is_git_repository",
    "pull_from_remote",
    "push_tag",
    "run_git_command",
    "show_commit_diff",
    "show_diff_between_commits",
    "show_enhanced_diff_between_commits",
    "show_local_changes_interactive",
    "show_working_directory_status",
]
